apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # Replace with your base64-encoded mongodb username
  mongo-password: bW9uZ29wYXNzd29yZA== # Replace with your base64-encoded mongodb password
